### ISSUE TITLE
Using 'GetPlayerStatsAsync' for user 'ImPants' throws exception

### ISSUE THREAD

**Issue by Hyper-Dragon** [nullablebool/ChessDotComSharp#2]
Using 'GetPlayerStatsAsync' for user 'ImPants' throws exception:

_Input string '2.17' is not a valid integer. Path 'chess_daily.record.timeout_percent', line 1, position 242._

'timeout_percent' for 'chess_daily' games may not be an int.  _FIX???_ _PlayerStats (ln. 52) should be...
[J("timeout_percent")] public double TimeoutPercent { get; set; }_

[ImPantsJson.txt](https://github.com/nullablebool/ChessDotComSharp/files/5419775/ImPantsJson.txt)

**Comment by nullablebool** [comment]
Feel free to submit a PR, otherwise I’ll get to it this weekend.
