### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by mattbruv** [nullablebool/ChessDotComSharp#5]
I get a 403 forbidden error when trying to do a simple API call through the library. When I visit the API URL through my browser everything works fine, but the library fails:

```c#
using ChessDotComSharp;
var client = new ChessDotComClient();
var x = await client.GetPlayerStatsAsync("hikaru");
```

`Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).`

It looks like it has something to do with the library triggering some kind of security measure in Cloudflare

<img width="792" alt="image" src="https://github.com/nullablebool/ChessDotComSharp/assets/5638426/aeab7ede-9615-470f-8abf-bc1c20326a27">
<img width="830" alt="image" src="https://github.com/nullablebool/ChessDotComSharp/assets/5638426/79cfd36e-552a-4b8b-817e-2948177192d5">

**Comment by mattbruv** [comment]
I'm playing around with making requests normally, and I was getting 403 errors using the normal `HttpClient`. When I added a spoofed user agent, it seems like cloudflare lets the request through:

```c#
var client = new HttpClient();
client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36");
var res = await client.GetAsync("https://api.chess.com/pub/player/hikaru");
```

You might have to spoof the user agent in this library to get it to work with cloudflare

**Comment by Hyper-Dragon** [comment]
Thanks @mattbruv - Agent string added

**Comment by mattbruv** [comment]
@Hyper-Dragon, although you fixed this years ago, I don't see the working version on Nuget? 
It still shows 1.0: https://www.nuget.org/packages/ChessDotComSharp

Also, while I figured this out in this issue, I just learned tonight that the actual reason for the 403 error is intentional and described here:

https://www.chess.com/announcements/view/breaking-change-user-agent-contact-info-required

> The user-agent should include a contact email and/or your chess.com username to allow communication about processes generating abnormal or excessive load on API endpoints.  The information will be used to let the developer know about issues and facilitate  fixes to allow continued API access.

Maybe we should add a string value to the constructor to allow the user of the library to identify themselves?
